/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package secinfocrypto.ui;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import secinfocrypto.user.DataBase;
import secinfocrypto.user.User;

/**
 *
 * @author bruno
 */
public class Login extends javax.swing.JPanel {

    private JFrame parent;
    
    /**
     * Creates new form Login
     */
    public Login(JFrame parent) {
        this.parent = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jTextFieldLogin = new javax.swing.JTextField();
        jButtonLogin = new javax.swing.JButton();
        jPasswordField = new javax.swing.JPasswordField();

        org.jdesktop.layout.GroupLayout jDialog1Layout = new org.jdesktop.layout.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );

        setLayout(new java.awt.BorderLayout());

        jTextFieldLogin.setText("login");
        add(jTextFieldLogin, java.awt.BorderLayout.PAGE_START);

        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        add(jButtonLogin, java.awt.BorderLayout.PAGE_END);

        jPasswordField.setText("password");
        add(jPasswordField, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        try {
            Logger.getLogger(Login.class.getName()).log(Level.FINE, "Login");
            
            User user = DataBase.getUser(this.jTextFieldLogin.getText(), this.jPasswordField.getPassword());
            
            this.parent.setContentPane(new UserInterface(this.parent, user.getFiles()));
            this.parent.pack();
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this.parent, ex.getMessage());
        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldLogin;
    // End of variables declaration//GEN-END:variables
}
