/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package secinfocrypto.ui;

import java.io.File;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JPanel;
import secinfocrypto.signature.Keys;
import secinfocrypto.signature.SignatureAlgorithm;
import secinfocrypto.signature.SignatureGenerator;
import secinfocrypto.signature.SignatureListener;

/**
 *
 * @author bruno
 */
public class UserInterface extends javax.swing.JPanel {

    private JFrame parent;
    private DefaultListModel listModel, algorithm;
    private Keys keys;
    byte[] signature;
    String fileName = "/Users/bruno/Desktop/Programmation_Android.pdf";

    public class GeneratorListener implements SignatureListener<byte[]> {
        
        JPanel parent;
        GeneratorListener(JPanel parent) {
            this.parent = parent;
        }

        @Override
        public void setProgress(int i) {
            jProgressBar1.setValue(i);
        }

        @Override
        public void setProcessInformation(String string) {
            jLabelCurrentAction.setText(string);
        }

        @Override
        public void setResult(byte[] result) {
            javax.swing.JOptionPane.showMessageDialog(this.parent, String.valueOf(result.length) +  " bytes");
        }
    }
    
        public class CheckerListener implements SignatureListener<Boolean> {
        
        JPanel parent;
        CheckerListener(JPanel parent) {
            this.parent = parent;
        }

        @Override
        public void setProgress(int i) {
            jProgressBar1.setValue(i);
        }

        @Override
        public void setProcessInformation(String string) {
            jLabelCurrentAction.setText(string);
        }

        @Override
        public void setResult(Boolean result) {
            javax.swing.JOptionPane.showMessageDialog(this.parent, String.valueOf(result));
        }
    }

    /**
     * Creates new form UserInterface
     */
    public UserInterface(JFrame parent) {
        this.parent = parent;
        this.listModel = new DefaultListModel();
        this.algorithm = new DefaultListModel();
        
        initComponents();
        
        this.jList1.setModel(this.listModel);
        
        this.keys = new Keys();
        try {
            keys.generation();
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(UserInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldPath = new javax.swing.JTextField();
        jButtonFiles = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jComboBox1 = new javax.swing.JComboBox();
        jButtonGenerate = new javax.swing.JButton();
        jButtonCheck = new javax.swing.JButton();
        jLabelCurrentAction = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldPath.setText("jTextField1");
        add(jTextFieldPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, -1));

        jButtonFiles.setText("File(s)");
        jButtonFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFilesActionPerformed(evt);
            }
        });
        add(jButtonFiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });
        add(jButtonLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, -1, -1));

        jProgressBar1.setStringPainted(true);
        add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 270, -1));

        jScrollPane1.setViewportView(jList1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 240, 330));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(SignatureAlgorithm.ALGORITHMS));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 110, -1));

        jButtonGenerate.setText("Sign");
        jButtonGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerateActionPerformed(evt);
            }
        });
        add(jButtonGenerate, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));

        jButtonCheck.setText("Check");
        jButtonCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckActionPerformed(evt);
            }
        });
        add(jButtonCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, -1));

        jLabelCurrentAction.setText("Current action");
        add(jLabelCurrentAction, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFilesActionPerformed
        Logger.getLogger(UserInterface.class.getName()).log(Level.FINE, "FileChooser");
        JFileChooser f = new JFileChooser();

        f.setMultiSelectionEnabled(true);
        if (f.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {

            File[] fs = f.getSelectedFiles();

            this.listModel.clear();
            for (File fi : fs) {
                this.listModel.addElement(fi.getName());
            }

            this.jList1.setSelectedIndex(0);




            this.jTextFieldPath.setText(fs[0].getAbsolutePath());
            for (int i = 1; i < fs.length; ++i) {

                fs[i].getName();
                fs[i].getAbsolutePath();

            }
        }
    }//GEN-LAST:event_jButtonFilesActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        Logger.getLogger(UserInterface.class.getName()).log(Level.FINE, "Logout");
        this.parent.setContentPane(new Login(this.parent));
        this.parent.pack();
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerateActionPerformed

        SignatureGenerator generator = new SignatureGenerator();
        generator.setSignatureListener(new GeneratorListener(this));
        generator.execute(fileName, keys.getPrivateKey(), SignatureAlgorithm.ALGORITHMS[1]);
    }//GEN-LAST:event_jButtonGenerateActionPerformed

    private void jButtonCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckActionPerformed
    }//GEN-LAST:event_jButtonCheckActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCheck;
    private javax.swing.JButton jButtonFiles;
    private javax.swing.JButton jButtonGenerate;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabelCurrentAction;
    private javax.swing.JList jList1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldPath;
    // End of variables declaration//GEN-END:variables
}
